# Generated by Django 5.0 on 2024-01-06 08:21

import django.db.models.deletion
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Dimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Единицы измерения',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('discount', models.IntegerField(default=0, verbose_name='Скидка в %')),
                ('weight', models.IntegerField(default=0, verbose_name='Вес')),
                ('calories', models.IntegerField(default=0, verbose_name='Калории')),
                ('proteins', models.IntegerField(default=0, verbose_name='Белки')),
                ('fats', models.IntegerField(default=0, verbose_name='Жири')),
                ('carbohydrates', models.IntegerField(default=0, verbose_name='углеводы')),
                ('storeg_temperature', models.IntegerField(default=0, verbose_name='Температура хранения')),
                ('sheif_life', models.IntegerField(default=0, verbose_name='Время хранения')),
                ('image', models.ImageField(default='null.png', upload_to=product.models.products_image_directory_path, verbose_name='Изображение')),
                ('is_activ', models.BooleanField(default=True, verbose_name='Активно?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Категория')),
                ('dimensions', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.dimensions', verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
