# Generated by Django 5.0 on 2024-01-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sheif_life',
            field=models.CharField(default=0, max_length=100, verbose_name='Время хранения'),
        ),
        migrations.AlterField(
            model_name='products',
            name='storeg_temperature',
            field=models.CharField(default=0, max_length=100, verbose_name='Температура хранения'),
        ),
    ]
