# Generated by Django 5.0 on 2024-01-06 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsinadress',
            options={'verbose_name_plural': 'Продукты в адресах'},
        ),
    ]
