# Generated by Django 5.0 on 2024-01-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllProductsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_discount', models.IntegerField(default=0, verbose_name='Общая скидка в %')),
            ],
            options={
                'verbose_name_plural': 'Настройки товаров',
            },
        ),
        migrations.CreateModel(
            name='ErrorClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.CharField(max_length=500)),
                ('sent_data', models.JSONField()),
                ('received_response', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Ошибки',
            },
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dev', models.BooleanField(default=False, verbose_name='Режим разработки')),
                ('is_disabled_cart', models.BooleanField(default=False, verbose_name='Отключить корзину')),
                ('is_disabled_online_pyment', models.BooleanField(default=False, verbose_name='Отключить онлайн оплату')),
                ('is_disabled_cash_pyment', models.BooleanField(default=False, verbose_name='Отключить отплату наличными')),
                ('is_disabled_auto_delivery', models.BooleanField(default=False, verbose_name='Отключить автодоставку')),
                ('is_disabled_people_delivery', models.BooleanField(default=False, verbose_name='Отклюить пешую доставку')),
                ('is_disabled_pickup_delivery', models.BooleanField(default=False, verbose_name='Отключить самовывоз')),
                ('is_disabled_reservation', models.BooleanField(default=False, verbose_name='Отключить бронирование столиков')),
                ('is_disabled_order', models.BooleanField(default=False, verbose_name='Отключить бронирование столиков')),
            ],
            options={
                'verbose_name_plural': 'Глобальные настройки',
            },
        ),
        migrations.CreateModel(
            name='OrderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_prise_auto', models.FloatField(verbose_name='Минимальная сумма заказа для автодоставки')),
                ('auto_free_delivery', models.BooleanField(default=True, verbose_name='Бесплатная доставка?')),
                ('auto_price_delivery', models.FloatField(blank=True, default=0.0, verbose_name='Цена атодоставки')),
                ('min_prise_people', models.FloatField(verbose_name='Минимальная сумма заказа для пешей доставки')),
                ('people_free_delivery', models.BooleanField(default=True, verbose_name='Бесплатная доставка')),
                ('people_price_delivery', models.FloatField(blank=True, default=0.0, verbose_name='Цена пешей доставки')),
                ('people_long_delivery', models.IntegerField(default=1500, verbose_name='Дальность пешей доставки')),
            ],
            options={
                'verbose_name_plural': 'Настройки заказов',
            },
        ),
    ]
