# Generated by Django 5.0 on 2024-01-06 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=500, verbose_name='Адрес')),
                ('entrance', models.IntegerField(blank=True, default='0', verbose_name='Подъезд')),
                ('floor', models.IntegerField(blank=True, default='0', verbose_name='Этаж')),
                ('door_code', models.IntegerField(blank=True, default='0', verbose_name='Код двери')),
                ('apartment', models.IntegerField(blank=True, default='0', verbose_name='Квартира')),
                ('long', models.FloatField(default=0.0, verbose_name='Долгота')),
                ('lat', models.FloatField(default=0.0, verbose_name='Широта')),
                ('is_activ', models.BooleanField(default=True, verbose_name='Активен?')),
            ],
            options={
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.CharField(blank=True, default='', max_length=10, verbose_name='Дата рождения')),
                ('adress', models.ManyToManyField(blank=True, to='lk.adress', verbose_name='Адреса')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
