# Generated by Django 5.0 on 2024-01-08 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('lk', '0001_initial'),
        ('market', '0002_alter_productsinadress_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='UserOrderHystory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Дата и время')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('is_call', models.BooleanField(default=True, verbose_name='Требуется звонок?')),
                ('discount', models.IntegerField(default=0)),
                ('pyment_id', models.CharField(blank=True, default='None', max_length=700, verbose_name='Номер оплаты')),
                ('is_pyment', models.BooleanField(default=False, verbose_name='Оплачено?')),
                ('market_adress', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='market.adress', verbose_name='Адрес приготовления')),
                ('products', models.ManyToManyField(blank=True, to='cart.productsincart', verbose_name='Продукты')),
                ('status', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='order.statusdelivery', verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('user_adress', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lk.adress', verbose_name='Адрес доставки')),
            ],
            options={
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
